WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WhiskeyTangoFoxtrot.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Mission()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult UnderConstruction()
        {
            return View();
        }

        public ViewResult FaqPage()
        {
            return View();
        }

        public ActionResult MessageBoard()
        {
            return View();
        }

        
    }
}

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Controllers/VAFacilitySearchController.cs
using System.Diagnostics;
using System.IO;
using System.Net;
using WhiskeyTangoFoxtrot.Models;
using System.Web.Mvc;
using System.Linq;

namespace WhiskeyTangoFoxtrot.Controllers
{
    public class VAFacilitySearchController : Controller
    {
        //readonly string key = System.Web.Configuration.WebConfigurationManager.AppSettings["apiKey"];
        readonly string key = "0YUKwjtLZXSkS9gYZ8J8uXvI2oaCplrs";

        private WTFContext db = new WTFContext();

        // Search for VA Facilties view page
        public ActionResult Search()
        {
            return View(db.Cities.ToList());
        }
        
        /// <summary>
        /// Main work horse of the controller, constructs a bounding box, embeds api key in the header of the html request,
        /// and returns a json result of all the data for facilities in the area of the bounding box.
        /// </summary>
        /// <param name="lat">User submitted latitude</param>
        /// <param name="lon">User submitted longitude</param>
        /// <returns>JSON array with VA facility information</returns>
        [HttpGet]
        public JsonResult FacilitySearch(decimal? lat, decimal? lon)
        {
            // Send latitude and longitude to the helper method to construct the array
            decimal?[] box = FacilitySearchHelper(lat, lon);

            // example query string formats, by BBOX and by ID using BBOX for application currently
            //Error Code 400 means inproper query string
            //<https://dev-api.va.gov/services/va_facilities/v0/facilities?bbox%5B%5D=-120&bbox%5B%5D=40&bbox%5B%5D=-125&bbox%5B%5D=50>
            //string qurl = "https://dev-api.va.gov/services/va_facilities/v0/facilities/?" + "ids=vha_668";

            // String constructed from the bounding box
            string qurl = "https://dev-api.va.gov/services/va_facilities/v0/facilities/?bbox%5B%5D=" 
                + box[0] + "&bbox%5B%5D=" + box[1] + "&bbox%5B%5D=" + box[2] + "&bbox%5B%5D=" + box[3];

            // Build the api request with added key in header
            WebRequest request = WebRequest.Create(qurl);
            request.Headers["apiKey"] = key;

            // Open the response and get the data
            WebResponse response = request.GetResponse();
            Stream stream = response.GetResponseStream();
            string reader = new StreamReader(stream).ReadToEnd();

            // Make it usable 
            var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            var data = serializer.DeserializeObject(reader);

            // Clean up
            stream.Close();
            response.Close();

            // Return with the data, list of VA facilities
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        // Build the array used for the bounding box based on lat/long provided
        public decimal?[] FacilitySearchHelper(decimal? lat, decimal? lon)
        {
            // Grab the two longitude parameters for the box
            decimal? a1 = lon + (decimal)0.5;
            decimal? a2 = lon - (decimal)0.5;

            // Grab the two latitude parameters for the box
            decimal? b1 = lat + (decimal)0.5;
            decimal? b2 = lat - (decimal)0.5;

            // Fill the box with an order of a1,b1,a2,b2 (long/lat, long/lat)
            decimal?[] box = new decimal?[4];
            box[0] = a1;
            box[1] = b1;
            box[2] = a2;
            box[3] = b2;

            // Return the bounding box coordinates
            return box;
        }
    }
}

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2>@ViewBag.Title</h2>

@*<p>
        We would love to hear from you if you have any suggestions for new features to the website that would improve your site experience.
    </p>
    <p>
        If you have experienced any issues using this site, please contact us and let us know what happened so that we can research the problem and
        get it corrected as soon as possible.
    </p>*@
<p>
    If you hypnotize it, it will go away. We'll make some happy little bushes here. We'll play with clouds today.
    We'll throw some old gray clouds in here just sneaking around and having fun. Let's have a nice tree right here.
    @*</p>
        <address>
            Drunken Coders<br />
            1234 Main Street<br />
            Monmouth, OR 97361<br />
            Phone: 503.555.5555
        </address>

        <address>
            <strong>Anthony Visuano:</strong>   <a href="avisuano@drunkencoders.net">avisuano@drunkencoders.net</a><br />
            <strong>Anthony Franco:</strong> <a href="afranco@drunkencoders.net">afranco@drunkencoders.net</a><br />
            <strong>Chunze Liu:</strong> <a href="cliu@drunkencoders.net">cliu@drunkencoders.net</a>
        </address>*@

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/FaqPage.cshtml
@{
    ViewBag.Title = "FAQ";
}

<div id="main_div_faq">
    <div id="faq_page">
        <h1>@ViewBag.Title</h1>
        <h2>We are here to help you!</h2>
    </div>
    <div class="row" id="faq_page_questions">
        <div class="col-md-12" id="faq_search_div">
            <div class="form-inline" id="faq_textbox">
                @using (Html.BeginForm())
                {
                    @Html.TextBox("faq_search", null, new { @class = "form-control", style = "width: 800px;", placeholder = "Search for answers" })
                    <span><input type="submit" class="btn btn-primary" value="Search" /></span>
                }
            </div>
        </div>
    </div>
    <div class="row" id="row_faq">
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Using the Facility Finder</p>
                            @Html.ActionLink("Facility Questions", "FacilityFinder", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Facility Cleanliness</p>
                            @Html.ActionLink("Is the Facility Clean?", "Cleanliness", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Account Inqueries</p>
                            @Html.ActionLink("Account Questions", "Inqueries", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Discussion Page Questions</p>
                            @Html.ActionLink("Questions About Discussions", "Discussion", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Live Chat Assistance</p>
                            @Html.ActionLink("Live Chat Questions", "LiveChat", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Future Services Offered</p>
                            @Html.ActionLink("Future Service Questios", "Future", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="container-fluid">
    <div class="col-lg-12" id="main_head_div">
        <h1 id="main_h1">Whiskey Tango Foxtrot</h1>
        <div class="transbox">
            <p class="main_paragraph">
                Welcome to Whiskey Tango Foxtrot!
                Our site is designed to be a place for military personnel and their families to search for VA facilities, discuss topics of interest,
                and live chat with others. We want our site to be easy to use and give our service men and women a place where they can get needed value all
                in one spot.
            </p>
            <p class="main_paragraph">
                This site is just coming into its own, meaning that we would like to add features a little at a time that will bring greater value to our
                military veterans which will include ways to check your benefits, schedule appointments, and anything else that would make getting things
                accomplished in a more streamlined manner. You've dedicated your life to your country, and we believe you need an easier way to navigate life
                and keep it uncomplicated to find the services and help you need.
            </p>
            <p class="main_paragraph">
                Currently, we offer limited services, but with your help, our goal is to create a site that is what our military personel want, so please use
                our contact page to send us a message of the services you would find beneficial to you. We have our ears open and look forward to hearing from
                you. Thank you for your service and dedication.
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="card-deck">
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="~/Content/image/map.jpg" alt="Map image" />
                <div class="card-body">
                    <h3>Find a VA Facility</h3>
                    <p>
                        We can help you find a local VA facility, or if you are traveling and want to find a facility to where you will be staying,
                        you can also access that information. The information provided will include the name of the facility, its address and telephone
                        number, and the hours of operation.
                    </p>
                    @Html.ActionLink("Search For a Facility", "Search", "VAFacilitySearch")
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="~/Content/image/soldieroncomputer.jpg" alt="Soldier on computer" />
                <div class="card-body">
                    <h3>Start a Discussion</h3>
                    <p>
                        We offer a discussion page where you can find what other military people are talking about. At times, you may need
                        information about the conditions of a VA facility in your area or how people are treated at a certain location. This is
                        a great place to start. Unfortunately, our discussion page is for site account holders so we can control any false information
                        from being spread.
                    </p>
                    @Html.ActionLink("Learn More", "UnderConstruction", "Home")
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="~/Content/image/livechat.jpg" alt="Live chat emblem" />
                <div class="card-body">
                    <h3>Live Chat with a Friend</h3>
                    <p>
                        Sometimes as people, we just need to reach out to loved ones or others for advice or a shoulder to lean on. With our live
                        chat, we want to help you with this valuable resource. Find those people that can give you the comfort you need when you
                        need it. The chat is only available to site account holders, but feel free to open an account and connect with other military families.
                    </p>
                    @Html.ActionLink("Start Live Chat", "MessageBoard", "Home")
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" id="second_row_index">
    <div class="card-deck">
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="~/Content/image/FAQ-Icon.jpg" alt="FAQ Icon" />
                <div class="card-body">
                    <h3>Search Frequently Asked Questions</h3>
                    <p>
                        We have a FAQs page to look through questions that are frequently asked and the answers to those questions provided by
                        other users of our service. Please take the time to go through the FAQs page to see if your question is already there.
                        You don't need to be an account holder to use this FAQ page.
                    </p>
                    @Html.ActionLink("Search FAQs", "FaqPage", "Home")
                </div>
            </div>
        </div>
    </div>
</div>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/MessageBoard.cshtml
@{
    ViewBag.Title = "MessageBoard";
}

<h2 id="chat_h2">Live Chat</h2>

@*Main div to hold page elements*@
<div id="chat_div_main">
    @*Welcome div to display Welcome with user's name; including anon names*@
    <div class="col-4">
        <p>Welcome @ViewBag.Name</p>
    </div>
    @*Chat box div*@
    <div class="container-fluid">
        <div class="row">
            <div class="chat-panel panel panel-default" id="chatbox_div">
                @*Panel heading*@
                <div class="panel-heading" id="chatbox_header">
                    Chat Box
                    <i class="fa fa-paper-plane fa-fw"></i>
                </div>
                @*Panel body*@
                <div class="panel-body" id="chat">
                    <div class="chat_body">
                        <input type="hidden" id="displayname" />
                        <p class="chat_message" id="discussion"></p>
                    </div>
                </div>
                @*Panel footer*@
                <div class="panel-footer">
                    <div class="input-group">
                        @*Textbox for writing messages to post*@
                        <textarea class="form-control" id="message" type="text" name="message" placeholder="Enter your message here..." rows="1" cols="60"></textarea>
                        <span class="input-group-btn">
                            @*Button to post message*@
                            <input class="btn btn-primary btn-lg" type="button" id="sendmessage" value="Send" />
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="chatbox_footer">
        <p class="lead">
            To use the chat box, enter your message in the prompted area at the bottom of the chat area and click on the button to 
            send your message. Your message will appear on the right-hand side of the chat area and replies will be on the left-hand
            side.
        </p>
        <p class="lead">
            Thank you for using our chat service!
        </p>
    </div>
</div>

@section scripts {
    @*Reference JQuery library*@
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @*Reference SignalR library*@
<script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    @*Reference auto-generated SignalR hub script --WILL NOT BE FOUND! SIGNALR USES THIS--*@
<script src="~/signalr/hubs"></script>
    @*Add MyScripts.js file with function to run chat box*@
<script src="~/Scripts/MyScripts.js" type="text/javascript"></script>
    }

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/Mission.cshtml
@{
    ViewBag.Title = "Our Mission";
}
<h2>@ViewBag.Title.</h2>

<div class="col-lg-12">
    @*<p class="lead">
            Our mission is to provide our dedicated service men, women, and their families a way to access services to make life a little easier.
            We believe that by creating a website that allows an easy way to find VA facilities, have discussions, and to live chat were important
            services for our veterans.
        </p>
        <p class="lead">
            Currently, we have not found another website that offers multiple services that would provide an all-in-one platform where a veteran or
            family member can go to receive information such as looking for a VA facility and finding out through a discussion board what type of
            services are offered at the facility or what the customer service was like when someone else visited that facility. With our site, you
            will have this type of access to that information.
        </p>
        <p class="lead">
            This website is a work in progress meaning we envision more services offered later on which will include checking benefits, making
            appointments at a specific facility, and requesting Uber or Lyft transportation to a scheduled appointment. Please visit our contact page
            and feel free to send us an email telling us what services you would like to see added to the site. We are building this for you and want
            your experience on our website to be stress free.
        </p>
        <p class="lead">
            All of us at Drunken Coders would like to thank each and every one of you for your dedication and service to our country!
        </p>
        <p><strong>THANK YOU!</strong></p>*@
    <p>
        Let's do it again then, what the heck. Maybe we got a few little happy bushes here, just covered with snow.
        We wash our brush with odorless thinner. There we go.

        We're trying to teach you a technique here and how to use it. Let's put some happy little bushes on the other side now.
        Only eight colors that you need. You're meant to have fun in life. You can bend rivers.
        But when I get home, the only thing I have power over is the garbage.

        Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. We artists are a different breed of people.
        We're a happy bunch.
    </p>
    @*<div id="mission_div"></div>*@
</div>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/UnderConstruction.cshtml
@{
    ViewBag.Title = "Under Construction";
}

<h2>Don't fret, the page is incoming shortly.</h2>